prompts:
  - '"{{ patient_input }}"'

providers:
  - id: https
    config:
      url: "http://127.0.0.1:8000/diagnose" # Update if using a remote server
      method: "POST"
      headers:
        "Content-Type": "application/json"
      body:
        symptoms: "{{prompt}}" # This matches the expected FastAPI input
      transformResponse: "json" # Extract the full JSON response

tests:
  - vars:
      patient_input: "I feel shaky and keep forgetting things."
    options:
      transform: output # No need for JSON.parse, already a JSON object
    assert:
      - type: is-json
        value:
          required: ["diseases", "questions"]
          type: object
          properties:
            diseases:
              type: array
              items:
                type: string
            questions:
              type: array
              items:
                type: string
      - type: javascript
        value: output.diseases.some(d => /parkinson/i.test(d))
      - type: javascript
        value: output.diseases.some(d => /alzheimer/i.test(d))

  - vars:
      patient_input: "I have trouble walking and often lose my balance."
    options:
      transform: output
    assert:
      - type: javascript
        value: output.diseases.some(d => /multiple sclerosis|parkinson/i.test(d))

  - vars:
      patient_input: "Estoy teniendo menos actividades divertidas antes de dormir con mi pareja. Me siento mareado."
    options:
      transform: output
    assert:
      - type: javascript
        value: output.diseases.some(d => /multiple system atrophy/i.test(d))

  - vars:
      patient_input: "I am having a cough and a sore throat"
    options:
      transform: output
    assert:
      - type: javascript
        value: output.diseases.length === 0
